<optgroup label="Иконки по телу">
  <option value="{{ asset('img/product/icons/icon-10.svg') }}" data-img-src="{{ asset('img/product/icons/icon-10.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-10.svg')){{ 'selected' }}@endif>Подтяжка кожи, anti age эффект</option>
  <option value="{{ asset('img/product/icons/icon-11.svg') }}" data-img-src="{{ asset('img/product/icons/icon-11.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-11.svg')){{ 'selected' }}@endif>Увлажнение</option>
  <option value="{{ asset('img/product/icons/icon-12.svg') }}" data-img-src="{{ asset('img/product/icons/icon-12.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-12.svg')){{ 'selected' }}@endif>Отшелушивание</option>
  <option value="{{ asset('img/product/icons/icon-13.svg') }}" data-img-src="{{ asset('img/product/icons/icon-13.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-13.svg')){{ 'selected' }}@endif>Сглаживание неровностей, уплотнение кожи, разграживание морщин</option>
  <option value="{{ asset('img/product/icons/icon-14.svg') }}" data-img-src="{{ asset('img/product/icons/icon-14.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-14.svg')){{ 'selected' }}@endif>Средство против роста волос</option>
  <option value="{{ asset('img/product/icons/icon-01.svg') }}" data-img-src="{{ asset('img/product/icons/icon-01.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-01.svg')){{ 'selected' }}@endif>Увлажнение 2</option>
  <option value="{{ asset('img/product/icons/icon-15.svg') }}" data-img-src="{{ asset('img/product/icons/icon-15.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-15.svg')){{ 'selected' }}@endif>Выведение лишней жидкости и снятие отечности, восстановление водного баланса кожи</option>
  <option value="{{ asset('img/product/icons/icon-16.svg') }}" data-img-src="{{ asset('img/product/icons/icon-16.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-16.svg')){{ 'selected' }}@endif>Борьба с цилюлитом</option>
  <option value="{{ asset('img/product/icons/icon-17.svg') }}" data-img-src="{{ asset('img/product/icons/icon-17.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-17.svg')){{ 'selected' }}@endif>Иконка</option>
  <option value="{{ asset('img/product/icons/icon-18.svg') }}" data-img-src="{{ asset('img/product/icons/icon-18.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-18.svg')){{ 'selected' }}@endif>Все что связано с трещинами и грубой кожей</option>
  <option value="{{ asset('img/product/icons/icon-19.svg') }}" data-img-src="{{ asset('img/product/icons/icon-19.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-19.svg')){{ 'selected' }}@endif>Устранение растяжек</option>
  <option value="{{ asset('img/product/icons/icon-06.svg') }}" data-img-src="{{ asset('img/product/icons/icon-06.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-06.svg')){{ 'selected' }}@endif>Смегчение и восстановление кожи</option>
  <option value="{{ asset('img/product/icons/icon-02.svg') }}" data-img-src="{{ asset('img/product/icons/icon-02.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-02.svg')){{ 'selected' }}@endif>Выравнивание цвета кожи, сияние волос</option>
  <option value="{{ asset('img/product/icons/icon-20.svg') }}" data-img-src="{{ asset('img/product/icons/icon-20.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-20.svg')){{ 'selected' }}@endif>Снятие воспаления</option>
  <option value="{{ asset('img/product/icons/icon-03.svg') }}" data-img-src="{{ asset('img/product/icons/icon-03.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-03.svg')){{ 'selected' }}@endif>Ускорение выработки коллагена и ластина</option>
  <option value="{{ asset('img/product/icons/icon-04.svg') }}" data-img-src="{{ asset('img/product/icons/icon-04.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-04.svg')){{ 'selected' }}@endif>Ускорение выработки коллагена и ластина 2</option>
  <option value="{{ asset('img/product/icons/icon-21.svg') }}" data-img-src="{{ asset('img/product/icons/icon-21.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-21.svg')){{ 'selected' }}@endif>Ускорение выработки коллагена и ластина 3</option>
  <option value="{{ asset('img/product/icons/icon-22.svg') }}" data-img-src="{{ asset('img/product/icons/icon-22.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-22.svg')){{ 'selected' }}@endif>Средство против роста волос</option>
</optgroup>
<optgroup label="Иконки по лицу">
  <option value="{{ asset('img/product/icons/icon-23.svg') }}" data-img-src="{{ asset('img/product/icons/icon-23.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-23.svg')){{ 'selected' }}@endif>Cальные железы</option>
  <option value="{{ asset('img/product/icons/icon-24.svg') }}" data-img-src="{{ asset('img/product/icons/icon-24.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-24.svg')){{ 'selected' }}@endif>Питание</option>
  <option value="{{ asset('img/product/icons/icon-25.svg') }}" data-img-src="{{ asset('img/product/icons/icon-25.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-25.svg')){{ 'selected' }}@endif>Нормализация работы сальных желез</option>
  <option value="{{ asset('img/product/icons/icon-26.svg') }}" data-img-src="{{ asset('img/product/icons/icon-26.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-26.svg')){{ 'selected' }}@endif>Быстрая впитываемость, не оставляет жирной пленки</option>
  <option value="{{ asset('img/product/icons/icon-27.svg') }}" data-img-src="{{ asset('img/product/icons/icon-27.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-27.svg')){{ 'selected' }}@endif>Охлаждение</option>
  <option value="{{ asset('img/product/icons/icon-28.svg') }}" data-img-src="{{ asset('img/product/icons/icon-28.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-28.svg')){{ 'selected' }}@endif>Восстановление волос</option>
  <option value="{{ asset('img/product/icons/icon-29.svg') }}" data-img-src="{{ asset('img/product/icons/icon-29.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-29.svg')){{ 'selected' }}@endif>Увлажение</option>
  <option value="{{ asset('img/product/icons/icon-05.svg') }}" data-img-src="{{ asset('img/product/icons/icon-05.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-05.svg')){{ 'selected' }}@endif>Увлажение 2</option>
  <option value="{{ asset('img/product/icons/icon-30.svg') }}" data-img-src="{{ asset('img/product/icons/icon-30.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-30.svg')){{ 'selected' }}@endif>Аромат</option>
  <option value="{{ asset('img/product/icons/icon-31.svg') }}" data-img-src="{{ asset('img/product/icons/icon-31.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-31.svg')){{ 'selected' }}@endif>Бережный уход</option>
</optgroup>
<optgroup label="Остальное">
  <option value="{{ asset('img/product/icons/icon-07.svg') }}" data-img-src="{{ asset('img/product/icons/icon-07.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-07.svg')){{ 'selected' }}@endif>Иконка 1</option>
  <option value="{{ asset('img/product/icons/icon-08.svg') }}" data-img-src="{{ asset('img/product/icons/icon-08.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-08.svg')){{ 'selected' }}@endif>Иконка 2</option>
  <option value="{{ asset('img/product/icons/icon-09.svg') }}" data-img-src="{{ asset('img/product/icons/icon-09.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-09.svg')){{ 'selected' }}@endif>Иконка 3</option>
  <option value="{{ asset('img/product/icons/icon-32.svg') }}" data-img-src="{{ asset('img/product/icons/icon-32.svg') }}" @if(isset($selected)&&$selected==asset('img/product/icons/icon-32.svg')){{ 'selected' }}@endif>Иконка 4</option>
</optgroup>
